spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cut
    user: root
    password: password
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  jpa:
    hibernate:
      ddl-auto: update

